-- SELECT first_name, last_name FROM EMPLOYEES e

SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES e WHERE EMPLOYEE_ID = 176;

SELECT LAST_NAME,SALARY FROM EMPLOYEES e WHERE SALARY >= 12000; 

SELECT LAST_NAME,SALARY FROM EMPLOYEES e WHERE SALARY NOT BETWEEN 5000 AND 12000;

SELECT e.LAST_NAME, e.DEPARTMENT_ID FROM EMPLOYEES e WHERE DEPARTMENT_ID IN(20,50) ORDER BY e.LAST_NAME, DEPARTMENT_ID DESC; 

SELECT e.LAST_NAME, e.SALARY, e.COMMISSION_PCT FROM EMPLOYEES e WHERE e.COMMISSION_PCT IS NOT NULL ORDER BY e.SALARY DESC, COMMISSION_PCT;

SELECT * FROM EMPLOYEES e WHERE SALARY NOT in(2500,3500,7000) AND JOB_ID IN('SA_REP','ST_CLERK');

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE LAST_NAME LIKE '%u%';

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '___a%';

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%a%' OR e.LAST_NAME LIKE '%e%' ORDER BY e.LAST_NAME; 

SELECT e.EMPLOYEE_ID, e.LAST_NAME FROM EMPLOYEES e WHERE e.LAST_NAME LIKE '%a%' AND e.LAST_NAME LIKE '%e%' ORDER BY e.LAST_NAME; 