-- salgrade: 급여 dept: department emp: employee

--SELECT
--	EMPNO AS "EMPLOYEE_NO",
--	ENAME AS "EMPLOYEE_NAME",
--	MGR AS "MANAGER",
--	SAL AS "SALARY",
--	COMM AS "COMMISSION",
--	DEPTNO AS "DEPARTMENT_NO"
--FROM
--	emp
--ORDER BY
--	DEPTNO DESC,
--	ENAME ASC;

-- SELECT * FROM emp WHERE Empno = 7839;

-- SELECT * FROM EMP e WHERE DEPTNO = 30 AND job = 'SALESMAN'

--SELECT * FROM EMP e WHERE e.sal >= 2500 AND e.JOB = 'ANALYST';
--
--SELECT * FROM EMP e WHERE e.JOB IN('MANAGER','SALESMAN','CLERK');
--
--SELECT * FROM EMP e WHERE e.JOB NOT IN('MANAGER','SALESMAN','CLERK')

SELECT e.EMPNO, e.ENAME, e.SAL, e.DEPTNO FROM EMP e WHERE e.DEPTNO = 10 
UNION ALL 
SELECT e.EMPNO, e.ENAME, e.SAL, e.DEPTNO FROM EMP e WHERE e.DEPTNO = 10; 