-- salgrade: 급여 dept: department emp: employee
--
--SELECT
--	EMPNO AS "EMPLOYEE_NO",
--	ENAME AS "EMPLOYEE_NAME",
--	MGR AS "MANAGER",
--	SAL AS "SALARY",
--	COMM AS "COMMISSION",
--	DEPTNO AS "DEPARTMENT_NO"
--FROM
--	emp
--ORDER BY
--	DEPTNO DESC,
--	ENAME ASC;
--
-- SELECT * FROM emp WHERE Empno = 7839;
--
-- SELECT * FROM EMP e WHERE DEPTNO = 30 AND job = 'SALESMAN'
--
--SELECT * FROM EMP e WHERE e.sal >= 2500 AND e.JOB = 'ANALYST';
--
--SELECT * FROM EMP e WHERE e.JOB IN('MANAGER','SALESMAN','CLERK');
--
--SELECT * FROM EMP e WHERE e.JOB NOT IN('MANAGER','SALESMAN','CLERK')
--
--SELECT e.EMPNO, e.ENAME, e.SAL, e.DEPTNO FROM EMP e WHERE e.DEPTNO = 10 
--UNION ALL 
--SELECT e.EMPNO, e.ENAME, e.SAL, e.DEPTNO FROM EMP e WHERE e.DEPTNO = 10; 

--SELECT e.ENAME, UPPER(e.ENAME), LOWER(e.ENAME), INITCAP(e.ENAME) 
--FROM EMP e 

--SELECT e.ENAME 
--FROM EMP e 
--WHERE e.ENAME LIKE '%S%';
--
--SELECT e.ENAME, INSTR(e.ENAME,'S') AS inst 
--FROM EMP e
--WHERE (INSTR(e.ENAME,'S')) != 0
--
--SELECT '010-1234-1535' AS 변경전,
--REPLACE('010-1234-1535','-',' ') AS REPLACE_1,
--REPLACE('010-1234-1535','-') AS replace_2
--FROM
--	dual; 
--	
--
--SELECT ADD_MONTHS(e.HIREDATE,240) 
--FROM EMP e 

--SELECT *
--FROM EMP e 
--WHERE e.HIREDATE > '1981-06-01'
--
--SELECT e.EMPNO, e.ENAME, e.SAL, e.COMM, NVL2(e.COMM,(e.SAL*12+e.COMM),e.SAL*12)
--FROM EMP e 

SELECT
	e.EMPNO ,
	e.ENAME ,
	TRUNC(e.SAL / 21.5, 3) AS 하루급여,
	ROUND(e.SAL / 172, 2) AS 시급
FROM
	EMP e;
	
SELECT 
	e.EMPNO,
	e.ENAME,
	e.HIREDATE,
	TO_CHAR(ADD_MONTHS(e.HIREDATE,3),'YYYY-MM-DD') AS R_JOB  
FROM EMP e;


SELECT 
	e.EMPNO,
	e.ENAME,
	e.MGR,
	DECODE(SUBSTR(MGR,0,2),'75','5555','76','6666','77','7777','78','8888','79',e.MGR,NULL,'0000') AS CHG_MGR
FROM EMP e;
